services:
  ansible-manager:
    build:
      dockerfile: Dockerfile_manager
    networks:
      - my_network

  ansible-node1:
    build:
      dockerfile: Dockerfile_node
    networks:
      - my_network

  ansible-node2:
    build:
      dockerfile: Dockerfile_node
    networks:
      - my_network
networks:
  my_network:

